{% set version = "1.0.8" %}

package:
  name: python-ternary
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/python-ternary/python-ternary-{{ version }}.tar.gz
  sha256: 41e7313db74ab2e24280797ed8073eccad4006429dfd87f6e66e7feba2aa64cd

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=2

test:
  imports:
    - ternary
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marcharper/python-ternary
  license: MIT
  license_file: LICENSE
  summary: Make ternary plots in matplotlib

extra:
  recipe-maintainers:
    - ocefpaf
    - marcharper
