{% set version = "1.0.5" %}

package:
  name: python-ternary
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-ternary/python-ternary-{{ version }}.tar.gz
  sha256: 1dc59ff2324e5d0c3727064eddf8832d571d2549b26285dfe7dc5d24b51071d5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - matplotlib >=1.4

test:
  imports:
    - ternary

about:
  home: https://github.com/marcharper/python-ternary
  license: MIT
  summary: 'Make ternary plots in matplotlib'

extra:
  recipe-maintainers:
    - ocefpaf
    - marcharper
