{% set version = "1.0.7" %}

package:
  name: python-ternary
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-ternary/python-ternary-{{ version }}.tar.gz
  sha256: 8447eeef6c4338f64e2234989e5d5fdf32bb281cb073a498619fa4c1df98c173

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - matplotlib-base >=1.4

test:
  imports:
    - ternary

about:
  home: https://github.com/marcharper/python-ternary
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Make ternary plots in matplotlib

extra:
  recipe-maintainers:
    - ocefpaf
    - marcharper
