{% set version = "1.0.3" %}

package:
  name: python-ternary
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-ternary/python-ternary-{{ version }}.tar.gz
  sha256: 42e49df2fb135af81f7426ea93aef8d7f4b10ccd78cebf64acf0ae257da2351d

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - matplotlib >=1.4

test:
  imports:
    - ternary

about:
  home: https://github.com/marcharper/python-ternary
  license: MIT
  license_file: license.txt
  summary: 'Make ternary plots in matplotlib.'

extra:
  recipe-maintainers:
    - ocefpaf
    - marcharper
