{% set version = "1.0.6" %}

package:
  name: python-ternary
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-ternary/python-ternary-{{ version }}.tar.gz
  sha256: 443b5c576032c14e52beb6d3708435f0492ba727839aee9bd8e14c2421d2ac46

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - matplotlib-base >=1.4

test:
  imports:
    - ternary

about:
  home: https://github.com/marcharper/python-ternary
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Make ternary plots in matplotlib'

extra:
  recipe-maintainers:
    - ocefpaf
    - marcharper
