{% set version = "1.0.4" %}

package:
  name: python-ternary
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-ternary/python-ternary-{{ version }}.tar.gz
  sha256: 024b885c3c1b0e828d3d4d35b0946c41e6a6514214cb2fdaa9b3560c4f8139ec

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - matplotlib >=1.4

test:
  imports:
    - ternary

about:
  home: https://github.com/marcharper/python-ternary
  license: MIT
  license_file: license.txt
  summary: 'Make ternary plots in matplotlib.'

extra:
  recipe-maintainers:
    - ocefpaf
    - marcharper
