travis:
  secure:
    BINSTAR_TOKEN: MNtXqm6Dij8PTR5dQqMAVDqzkZYQveNs0/41bHUk8ilJG192XE6zSKlMWv5MfZlQ7KOcJ2n3pWudg7ZbIALWg7j0s0PjeC11vkkUFIXm2UF0H1PflAgefkVwn4iqk9Igsf56ub7Ke+rmNjgskhLvPDi9IjBj4X0OtiEj6awMKsfJGf8bYLHIQOAkia7B8c6lwsm9icLCwfaaaAVg0byfgW76Wm0rJwNGW1ixtsirTK9yjPFjv8LQa7BPPWNub8vHXjNEt50GxjumJ+4w8IzbAHum35swGbQ1y0pOa5579AsH7o9EQ+n0LFHs2FwGKNs9EsBX3mgiafya+YYgDi402BOOpe0KCzdRPKLM3zEUdN1YrnwlyTG+h2FiHQSXBG16xNJyKVqglp0tc8xjuKFlBtUNUu6eqLUfwgDRSpUyKjDepBf3tmgJVoaSUl4TlffWwknKIMOeC8iJ2SgUbD/ghm3tG4ouHoyAL7edHUg73CDd9g6h+1Bj+UHRrsnkFCdE1kOtrwqSY02AI+LbUgCMBFtD3+4H9Z2JExsQmxLb6a0mbq4j38Fe/xl3rjlwWjjiIa+KOrfl6RXkUDHkMsYMimi7oYju8cduG980MsF+w2TkGBdh3PB1kHotXb1+PqkvUDBNgypc6wT8mlqQD7fSuzVadfVOVF95iWQRahQvl+k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
