travis:
  secure:
    BINSTAR_TOKEN: MtRIB+GtTVmfAjaJcXr2YCoB5kAnRPKQoigxgHRVQGjm+GwIoNRzduDICyUcEDNydaWlxsxNDZs1g+X4LSwY1dFEEVQibuq0oRTL2JUmNxlxJUsWPmdVD1pQrHfYylMqdb33aOqhUxW0JhswFovjsrr9NK/PtprVGTxZ4jWDQ/dmiKgmLiixBBfqSzTw3pc4KP/iKb/asAk35pan1FIdBjRtBrJJfbEXv7AgkRyZZ3LLrrPFK7P2dAawyR7+XFsMspASOekRrShxYJoJwLJIXBBIjgBjekmxmUgHPfevBgHfN/DPiDvXnmI8GvSlNggYMqZT6JRCyDYh/nBQ7TKBPlXXFcdse11TlcoIu/MGVu+BYRwtWL2iJhiYRZGZciRwzqvfVvfgTTFPRKKcNDzApQblAHeBkc2Wfosxs4OfLpl+R4+aOG8LcneIp6X8jO0ETx9G9j6szmbmY/MUAy3d3XWonBVr5CehktDRFwKo1Jk8Zwj3RjLqqTUkRM8uGhtECCcfstup6kVamRQ3hMsNz2AYxwMRuDKkmfbWxyBFNHTSVwt1D6SG9LCogSkUpytIsLEGn5JxEFaueZDiQE7LEkKPuwFe9MKhXIOeDOOzGbMO2Sa+/66+PanAm2r008l8u834ck0Nrw1DR+pPaMYGMN02yfHMEke3mHpKf7ItJJg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
