travis:
  secure:
    BINSTAR_TOKEN: KyDeNGM60Z8eH1UjZtY2V7idm3Ze4XeaDfmvNsymOaGw8awxlMdJlQ2meaAP6U/mFkoccoHhomk+YobM8DVvAoN72sXYZsFdrW/MLjWHTqInSKt1p2I7vLECOO8lS4zmrYAyZVHuqhKqw3xDvC6I2sx9/XNBwpzsmTKUzTSft4e76ZBvNDd/TKSOiWvAYK/F5kjSNB+Gdx8hhKH1tokVAMPxIlJ4TP/3CemN8A3bX6B8zBto9uYhZF1fNC2ypxxIUKV6pi96VJ6BGDHsosh1Q6q36+5Q74jN4gnEaVEgQOrDjS6cZkuR9VZM8a7m09vR4Q8ooP+MNotZz5o7cbSJhs9PAPXIwwWapZtztQ52w18VaRb69j0fbCGjMfACDdBxr1O6hvtqU8pW4hQqltEqDInrckp0Af6can/FRRqiW3x4GN2FLLXbntwjgoMfMA8RiEBa9eZSrtg0VEXWMWaGz8SUygFOfKnzwFQ2+ssMS2XSun8h3h2+5vLzmY3yKBpRyN9ObFLePCOoINHwq3QX2o/PyPvbQKYhIfzw3o/HU7vmCZZbA40h0cWFTVmSVNTtG1gUdg/hT73Chmn95JlZtUQ582SeWlViaX8m345Fdv87KPJ9bOC6mmI/jEXkhv7jTbF+WWpRUXA5DfZPIIAvSpm32v+mSGjn7vUWlmZ1aVs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
